FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

# latest git
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:git-core/ppa

RUN apt-get update && apt-get install -y \ 
		      git\
		      apt-utils \ 
		      curl \
		      build-essential \
		      libssl-dev \
		      libreadline-dev \
		      zlib1g-dev \
		      sqlite3 \
		      libsqlite3-dev \
		      openssh-server \
		      zsh \
		      sudo \
		      locales

RUN apt-get -qq install --no-install-recommends  vim > /dev/null

RUN locale-gen en_US.UTF-8

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

RUN echo 'LANGUAGE=en_US.UTF-8' >> /etc/environment
RUN echo 'LANG=en_US.UTF-8' >> /etc/environment
RUN echo 'LC_ALL=en_US.UTF-8' >> /etc/environment
# RUN locale-gen en_US.UTF-8
# RUN dpkg-reconfigure locales
