version: "3.3"

services:
  env:  
    image: sandbox:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - '20122:22'
    environment:
      TZ: Asia/Seoul
    networks:
      - sandbox 

    restart: always

networks:
  sandbox: