FROM rbenv:latest


## Change here to set personal information ##
ENV USER_NAME jekyll
ARG SOURCE_DIR=src
ARG GIT_URL=https://github.com/jerry901
ARG REPO_NAME=jerry901.github.io.git
ARG RUBY_VERSION=2.6.3
## end ##

RUN adduser --gecos '' --disabled-password $USER_NAME

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y openssh-server 

# install ruby
RUN rbenv install $RUBY_VERSION 
RUN rbenv global $RUBY_VERSION

# install bundler
RUN gem install bundler

RUN usermod -G rbenv jekyll

ENV HOME /home/$USER_NAME
RUN mkdir -p $HOME/$SOURCE_DIR

WORKDIR $HOME/$SOURCE_DIR
ENV GEM_HOME $HOME/.gem
ENV GEM_PATH $HOME/.gem

RUN mkdir $HOME/$SOURCE_DIR/$REPO_NAME
RUN git clone $GIT_URL/$REPO_NAME $HOME/$SOURCE_DIR/$REPO_NAME


# set path variable
RUN echo 'export RBENV_ROOT=/usr/local/rbenv' >> ~/.bashrc
RUN echo 'export PATH=${RBENV_ROOT}/shims:${RBENV_ROOT}/bin:${RBENV_ROOT}/plugins/ruby-build/bin:${PATH}' >> ~/.bashrc

RUN echo 'export GEM_HOME=${HOME}/.gem' >> ~/.bashrc
RUN echo 'export GEM_PATH=${HOME}/.gem' >> ~/.bashrc
RUN echo 'export PATH=${HOME}/.gem/bin:${PATH}' >> ~/.bashrc

RUN echo 'set -o vi' >> ~/.bashrc

RUN bash

# install app dependencies
RUN (cd $HOME/$SOURCE_DIR/$REPO_NAME && bundle install)

RUN chgrp -R rbenv $HOME
RUN chmod -R g+rwxXs $HOME

ENTRYPOINT service ssh restart && bash

EXPOSE 4000
EXPOSE 22