FROM ubuntu:20.04

# update apt cache and install dependencies
RUN apt-get update && apt-get install git curl build-essential libssl-dev libreadline-dev zlib1g-dev sqlite3 libsqlite3-dev -y

# add app user
# set user to jekyll  
# set home paht
RUN adduser --gecos '' --disabled-password jekyll
USER jekyll 
ENV HOME /home/jekyll

# set rbenv, ruby-build bin paths
ENV PATH $HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv/plugins/ruby-build/bin:$PATH

# clone rbenv
RUN git clone git://github.com/sstephenson/rbenv.git ~/.rbenv

# clone ruby-build
RUN git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# set working directory to project src
WORKDIR /src

RUN git clone https://github.com/jerry901/jerry901.github.io.git
# add Gemfile, Gemfile.lock, .ruby-version to docker
# ADD Gemfile Gemfile.lock .ruby-version ./

# install ruby
RUN rbenv install 2.6.3
RUN rbenv global 2.6.3

# install bundler
RUN gem install bundler

# install app dependencies
RUN bundle install

# run rails
# CMD ["bundle", "exec", "rails", "server"]

EXPOSE 3000