FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

## Change here to set persnal evironment ##
ARG USER_NAME=rbenv
ARG GIT_URL=https://github.com/jerry901
ARG REPO_NAME=jerry901.github.io.git
ARG SOURCE_DIR=src
ARG RUBY_VERSION=2.6.3
## Personal setting end ##

# root commands
# update apt cache and install dependencies
RUN apt-get update && apt-get install vim apt-utils git curl build-essential libssl-dev libreadline-dev zlib1g-dev sqlite3 libsqlite3-dev -y
RUN apt-get install -y openssh-server 

RUN adduser --gecos '' --disabled-password $USER_NAME

USER $USER_NAME

ENV HOME /home/$USER_NAME

# user commands 
# mkdir first to avoid permission denied error; when WORKDIR doesn't exist, it creates the directory as a root previllage
RUN mkdir -p ~/$SOURCE_DIR
WORKDIR $HOME/$SOURCE_DIR

# set rbenv, ruby-build bin paths
ENV PATH $HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv/plugins/ruby-build/bin:$PATH

# clone rbenv
RUN git clone git://github.com/sstephenson/rbenv.git ~/.rbenv

# clone ruby-build
RUN git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build

# install ruby
RUN rbenv install $RUBY_VERSION
RUN rbenv global $RUBY_VERSION

# install bundler
RUN gem install bundler

########## Personal Settings ##########

RUN mkdir -p ~/$SOURCE_DIR/$REPO_NAME
RUN git clone $GIT_URL/$REPO_NAME ~/$SOURCE_DIR/$REPO_NAME
# add Gemfile, Gemfile.lock, .ruby-version to docker
# ADD Gemfile Gemfile.lock .ruby-version ./

# install app dependencies
RUN (cd ~/$SOURCE_DIR/$REPO_NAME && bundle install)

RUN echo 'eval \"$(rbenv init -)\" #changed this to below because of slow startup' >> ~/.bashrc
RUN echo 'set -o vi' >> ~/.bashrc
ENTRYPOINT service ssh restart && bash

EXPOSE 4000
EXPOSE 22

#######################################