version: "3.3"

services:
  env:  
    image: rbenv:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      TZ: Asia/Seoul
    networks:
      - rbenv

    restart: always

networks:
  rbenv: