FROM ubun2:latest

# set this argument to install openssh-server without any keyboard interactions.
ARG DEBIAN_FRONTEND=noninteractive

# update apt cache and install library dependencies.

# set default shell to ZSH.
RUN chsh -s $(which zsh);

# make a directory for rbenv, ruby-build.

# clone rbenv.
RUN git clone git://github.com/sstephenson/rbenv.git /usr/local/rbenv

RUN mkdir -p /usr/local/rbenv/plugins; \
    git clone git://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build

# change group, permisson of rbenv so that any other users can use rbenv.
RUN chgrp -R staff /usr/local/rbenv; \ 
    chmod -R g+rwxXs /usr/local/rbenv;

# set bin paths for rbenv, ruby-build .
ENV RBENV_ROOT /usr/local/rbenv  
ENV PATH $RBENV_ROOT/shims:$RBENV_ROOT/bin:$RBENV_ROOT/plugins/ruby-build/bin:$PATH

# set environment variables in case of attaching trough a SSH connection.
RUN echo "export RBENV_ROOT=$(echo $RBENV_ROOT)" >> ~/.zshrc; \
    echo "export PATH=$(echo $PATH)" >> ~/.zshrc; \ 
    echo 'eval "$(rbenv init -)" #changed this to below because of slow startup' >> ~/.zshrc; \
    echo "export LC_ALL=en_US.UTF-8" >> ~/.zshrc 
