version: "3.3"

services:
  local:  
    image: mysql:5.7
    ports:
      - 3000:3000
      - 2222:22
    environment:
      TZ: Asia/Seoul
    networks:
      - jekyll
    restart: always

networks:
  backend: