FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

## Change here to set persnal evironment ##

## Personal setting end ##

# root commands
# update apt cache and install dependencies
RUN apt-get update && apt-get install -y \ 
		      vim \ 
		      apt-utils \ 
		      git \
		      curl \
		      build-essential \
		      libssl-dev \
		      libreadline-dev \
		      zlib1g-dev \
		      sqlite3 \
		      libsqlite3-dev \
		      openssh-server

# set rbenv, ruby-build bin paths
RUN groupadd rbenv

# clone rbenv
RUN mkdir -p /usr/local/rbenv

RUN git clone git://github.com/sstephenson/rbenv.git /usr/local/rbenv

# clone ruby-build
RUN mkdir -p /usr/local/rbenv/plugins
RUN mkdir -p /usr/local/rbenv/plugins/ruby-build

RUN git clone git://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build

RUN chgrp -R rbenv /usr/local/rbenv
RUN chmod -R g+rwxXs /usr/local/rbenv

ENV RBENV_ROOT=/usr/local/rbenv
ENV PATH $RBENV_ROOT/shims:$RBENV_ROOT/bin:$RBENV_ROOT/plugins/ruby-build/bin:$PATH

RUN echo 'export RBENV_ROOT=/usr/local/rbenv' >> ~/.bashrc
RUN echo 'export PATH=${RBENV_ROOT}/shims:${RBENV_ROOT}/bin:${RBENV_ROOT}/plugins/ruby-build/bin:${PATH}' >> ~/.bashrc

RUN echo 'eval "$(rbenv init -)" #changed this to below because of slow startup' >> ~/.bashrc
