version: "3.3"

services:
  local:  
    image: ssh:latest 
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    ports:
      - "20022:22"
    environment:
      TZ: Asia/Seoul
    networks:
      - ssh

    restart: always
networks:
  ssh: